import {
  Video,
  Plus,
  Folder,
  Save,
  MonitorPlay,
  Download,
  Keyboard,
  X,
  SkipBack,
  SkipForward,
  Pause,
  Play,
  Square,
  Scissors,
  Music,
  Type,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  Key,
  Move,
  Maximize2,
  Minimize2,
  RotateCw,
  Clock,
  Upload,
  Layers,
  ChevronDown,
  LayoutGrid,
  Pencil,
  Trash2,
  ChevronUp,
  ZoomIn,
  ZoomOut,
  Volume2,
  VolumeX,
  Sparkles,
  Copy,
  Magnet,
  AudioWaveform,
  Crop,
  Repeat,
} from 'lucide-react';

export const icons = {
  video: Video,
  plus: Plus,
  folder: Folder,
  save: Save,
  screen: MonitorPlay,
  download: Download,
  keyboard: Keyboard,
  close: X,
  skipBack: SkipBack,
  skipForward: SkipForward,
  pause: Pause,
  play: Play,
  stop: Square,
  cut: Scissors,
  audio: Music,
  text: Type,
  eye: Eye,
  eyeOff: EyeOff,
  lock: Lock,
  unlock: Unlock,
  keyframe: Key,
  move: Move,
  maximize: Maximize2,
  minimize: Minimize2,
  rotate: RotateCw,
  clock: Clock,
  upload: Upload,
  layers: Layers,
  chevronDown: ChevronDown,
  layoutGrid: LayoutGrid,
  pencil: Pencil,
  trash: Trash2,
  chevronUp: ChevronUp,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
  volume: Volume2,
  volumeMute: VolumeX,
  workflow: Sparkles,
  copy: Copy,
  magnet: Magnet,
  waveform: AudioWaveform,
  crop: Crop,
  repeat: Repeat,
};

